name: Generate Datas

on:
  schedule: # execute every 6 hours
    - cron: "* */6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: generate-snake-game-from-github-contribution-grid
        id: snake-gif
        uses: Platane/snk@master
        with:
          github_user_name: orlandinivictor
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
